#!/bin/sh

# Link this script into /etc/munin/plugins, and add the name of the 
# table you want to monitor after the underscore. To monitor items:
# 
# sudo ln -s /home/user/munin-koha/koha_ /etc/munin/plugins/koha_items
# 
# This script needs to run as root, so add this to the file
# /etc/munin/plugin-conf.d/munin-node:
# 
# [koha_*]
# user root
# 
# And don't forget to restart munin afterwards: 
# 
# sudo /etc/init.d/munin-node restart

table=${0##*koha_}

case $1 in
  config)
    echo "graph_args -l 0"
    echo "graph_title Koha $table"
    echo "graph_vlabel $table"
    for name in $(koha-list)
    do
      echo "$name.label $name"
    done
    exit 0;;
esac

for name in $(koha-list)
do

  # kohaconfig="/etc/koha/sites/$name/koha-conf.xml"
  # 
  # mysqlhost="$( xmlstarlet sel -t -v 'yazgfs/config/hostname' $kohaconfig )"
  # mysqldb="$( xmlstarlet sel -t -v 'yazgfs/config/database' $kohaconfig )"
  # mysqluser="$( xmlstarlet sel -t -v 'yazgfs/config/user' $kohaconfig )"
  # mysqlpass="$( xmlstarlet sel -t -v 'yazgfs/config/pass' $kohaconfig )"
  # 
  echo -n "$name.value "
  # mysql --host="$mysqlhost" --user="$mysqluser" --password="$mysqlpass" \
  #   -e "SELECT COUNT(*) as count FROM $table\G" "$mysqldb" | grep count | cut -d' ' -f2
  echo "SELECT COUNT(*) as count FROM $table\G" | koha-mysql $name | grep count | cut -d' ' -f2

done
