#!/bin/sh

# Link this script into /etc/munin/plugins, and add the name of the 
# table you want to monitor after the underscore. To monitor items:
# 
# sudo ln -s /home/user/munin-koha/koha_ /etc/munin/plugins/koha_items
# 
# This script needs to run as root, so add this to the file
# /etc/munin/plugin-conf.d/munin-node:
# 
# [koha_*]
# user root
# 
# And don't forget to restart munin afterwards: 
# 
# sudo /etc/init.d/munin-node restart

input=${0##*koha_}
table=$( echo "$input" | cut -d _ -f 1 )
inst=$(  echo "$input" | cut -d _ -f 2 )

case $1 in
  config)
    echo "graph_args -l 0"
    echo "graph_title Koha $table for $inst"
    echo "graph_vlabel Number of rows"
    echo "graph_category Koha-$inst"
    echo "$table.label $table"
    exit 0;;
esac

echo -n "$table.value "
echo "SELECT COUNT(*) as count FROM $table\G" | koha-mysql $inst | grep count | cut -d' ' -f2
